apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresql
provisioner: kubernetes.io/no-provisioner
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  labels:
    type: local
spec:
  storageClassName: postgresql
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wyou/data/partition1/pvs/pv-postgresql"
