apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ragflow-es
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 32Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/wyou/data/partition1/pvs/pv-ragflow/es"
