apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vvfanny/data/PV/gitlab/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vvfanny/data/PV/gitlab/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-logs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vvfanny/data/PV/gitlab/logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      name: http
    - port: 22
      targetPort: 22
      nodePort: 30022
      name: ssh
  selector:
    app: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      nodeName: vvfanny
      containers:
        - name: gitlab
          image: docker.io/gitlab/gitlab-ce:17.9.1-ce.0
          #image: localhost/fedora-devel:latest
          imagePullPolicy: Never
          #securityContext:
            #privileged: true
          ports:
            - containerPort: 80
              name: http
            - containerPort: 22
              name: ssh
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'http://gitlab.wyou.com';
                gitlab_rails['gitlab_shell_ssh_port'] = 22;
                nginx['redirect_http_to_https'] = false;
                nginx['ssl_enabled'] = false;
                gitlab_rails['gitlab_signin_enabled'] = false;
                prometheus_monitoring['enable'] = false;
                gitlab_rails['gitlab_two_factor_enabled'] = false;
                gitlab_rails['rack_attack_git_basic_auth'] = false;
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
      volumes:
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: gitlab-config
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: gitlab-logs
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data
