apiVersion: v1
kind: Pod
metadata:
 name: fedora-ptp
 namespace: default
spec:
 containers:
 - name: fedora-ptp
   image: localhost/fedora-ptp:latest
   imagePullPolicy: Never
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
   resources:
    limits:
      wyou/ptp: 1   
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
