apiVersion: v1
kind: Pod
metadata:
 name: fedora-ptp2
 namespace: default
spec:
 containers:
 - name: fedora-ptp2
   image: localhost/fedora-ptp2:latest
   imagePullPolicy: Never
   securityContext:
     runAsUser: 1000  # UID of the non-root user
     runAsGroup: 1000 # GID of the non-root user
     allowPrivilegeEscalation: false
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
   resources:
    limits:
      wyou/mrvl-ptp: 1   
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
