apiVersion: v1
kind: Pod
metadata:
 name: fedora-dp2
 namespace: default
spec:
 containers:
 - name: fedora-dp2
   image: localhost/fedora-dp2:latest
   imagePullPolicy: Never
   command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   args: [ "while true; do sleep 10; done;" ]
   volumeMounts:
   - name: device-plugins
     mountPath: /var/lib/kubelet/plugins_registry
 volumes:
 - name: device-plugins
   hostPath:
     path: /var/lib/kubelet/plugins_registry
     type: DirectoryOrCreate

 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
