apiVersion: v1
kind: Pod
metadata:
 name: fedora
 namespace: default
spec:
 hostNetwork: true
 #hostIPC: true
 containers:
 - name: fedora
   image: localhost/fedora-ioctl:latest
   imagePullPolicy: IfNotPresent
   #command: [ "/bin/bash", "-c", "--" ]       # You need to run some task inside a container to keep it running
   #args: [ "while true; do sleep 10; done;" ]
   securityContext:
    runAsUser: 999  # Replace with the desired user ID
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      add:
      - NET_ADMIN
 restartPolicy: Never
 tolerations:
 - key: "key"
   operator: "Exists"
   effect: "NoSchedule"
