apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-model-on-pv
  namespace: default
spec:
  replicas: 1  # Using 1 replica since we're using GPU
  selector:
    matchLabels:
      app: ollama-model
  template:
    metadata:
      labels:
        app: ollama-model
    spec:
      hostNetwork: true
      hostIPC: true
      containers:
      - name: ollama-model-on-pv
        image: docker.io/ollama/ollama:latest
        imagePullPolicy: Never
        resources:
          limits:
            nvidia.com/gpu: 1
        command: ["/bin/bash", "-c", "--"]
        args: ["while true; do sleep 10; done;"]
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: pvc-ollama
      tolerations:
      - key: "key"
        operator: "Exists"
        effect: "NoSchedule"
