apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: default
spec:
  selector:
    app: ollama-model
  ports:
    - protocol: TCP
      port: 13140
      targetPort: 11434
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-model-on-pv
  namespace: default
spec:
  replicas: 1  # Using 1 replica since we're using GPU
  selector:
    matchLabels:
      app: ollama-model
  template:
    metadata:
      labels:
        app: ollama-model
      annotations:
        # Pod 进入 Failed 状态 60 秒后自动删除
        ttl-after-finished.kubernetes.io: "60"
    spec:
      #hostNetwork: true
      #hostIPC: true
      containers:
      - name: ollama-model-on-pv
        image: docker.io/ollama/ollama:latest
        imagePullPolicy: Never
        command: ["ollama"]
        args: ["serve"]
        #command: ["/bin/bash", "-c", "--"]
        #args: ["while true; do sleep 10; done;"]
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
        - containerPort: 11434
          protocol: TCP
        volumeMounts:
        - name: ollama-storage
          mountPath: /root/.ollama
      volumes:
      - name: ollama-storage
        persistentVolumeClaim:
          claimName: pvc-ollama
      tolerations:
      - key: "key"
        operator: "Exists"
        effect: "NoSchedule"
